FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch

# Install build tools and remove layer cache afterwards
RUN apt-get -q update && apt-get install -yq --no-install-recommends \
	build-essential \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

# Switch to working directory for our app
WORKDIR /usr/src/app

# Copy all the source code in.
COPY ./src .

# Compile our source code
RUN gcc main.c -o flush

# Launch our binary on container startup.
CMD ["bash", "/usr/src/app/copy.sh"]